### ISSUE TITLE
InternalServerError

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ignition#12]
https://github.com/TryGhost/Ignition/blob/master/lib/errors/index.js#L19
This is the default values for the base error prototype.
It was suggested to re-add the InternalServerError anyway, because it's hard to know that you have to use the basic error prototype to instantiate an InternalServerError.

**Comment by ErisDS** [comment]
I published the config update as 2.0.0-alpha.1, it'd be good to get this in for 2.0.0
