### ISSUE TITLE
Wrong log level in lib/logging/GhostLogger.js 

### ISSUE THREAD

**Issue by sahand12** [TryGhost/Ignition#30]
You are trying to log errors to a rotating file but you are using the default log level.
at line 130:
current: `level: this.level`
must be: `level: "error"`

**Comment by kirrg001** [comment]
Hey @sahand12 👋  Thanks for your report.

Your assumption seems correct, but could you please share what happens if the level is set to default for rotating error files?

**Comment by sahand12** [comment]
you log everything with log level equal or above the default log level, not just 'error' and 'fatal' level.
that's why you have two files, one for all logs and one for just errors.

**Comment by kirrg001** [comment]
yeah i can confirm 👍 Would you like to create a PR?

**Comment by sahand12** [comment]
yeah, sure. do you have a guideline for that?

**Comment by kirrg001** [comment]
You can follow our Ghost guideline.

https://github.com/TryGhost/Ghost/wiki/Git-workflow#notes-on-writing-good-commit-messages
