### ISSUE TITLE
Logging errors with context messages results in [object Object]

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ignition#45]
In some cases, we get errors from other node modules or services and we might want to log out the original error before mutating it into a Ghost-Ignition error.

```
someAsyncCallTo3rdPartyCode(err, res) {
  if (err) {
   return logger.error({err: err}, 'Got an error from 3rd party service X');
  }
  ... handle success...
});
```

Passing `{err: err}` to the logger should result in the error being serialized into a familiar format, but at the moment, if you also pass an additional message, then what you get output is:

`[2017-07-03 15:50:08] ERROR [object Object]Got an error from 3rd party service X`

This is a bit confusing because, [the Bunyan docs say this should work](https://github.com/trentm/node-bunyan#log-method-api) and I have used this pattern in other apps which use Bunyan directly.

It seems there is code in Ghost Ignition, specifically in GhostLogger, that overwrites Bunyan's behaviour and does it differently? https://github.com/TryGhost/Ignition/blob/master/lib/logging/GhostLogger.js#L243

I am not clear enough on what the purpose of this code is to know if I can fix it :)

**Comment by ErisDS** [comment]
@kirrg001 please please can haz fix?

**Comment by kirrg001** [comment]
@ErisDS 👍
