### ISSUE TITLE
loggly stream slows down process

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ignition#54]
Have not yet investigated.

If i enable `loggly` it slows down responses when doing load testing.

- [x] research
- [x] fix matching condition

If i am not using the loggly stream, it's much faster and does not stuck with responses.

**Comment by kirrg001** [comment]
I can't reproduce this anymore. Closing.

**Comment by kirrg001** [comment]
I need to investigate this again. I saw a similar behaviour again on a different server.

Response times go up if i do load testing with `loggly` transport.
There is either a bug in Ignition or in the third party lib.

**Comment by kirrg001** [comment]
Okay i found the cause.

We are using `json-stringify-safe` to match a string in the req/res object for loggly. 

e.g. `match: level:critical`

The match is sync operation and just takes ages, because the req/res object is A to big and B maybe the lib is not optimised for such big objects (see https://github.com/moll/json-stringify-safe/issues/16).

I'll simply reduce the logic for now. This will limit the match feature to only match errors properties, but that's fine for now, because the loggly stream only supports sending errors currently (the level is hardcoded to `error` - all e.g. info logs are ignored anyway).

**Comment by pysysops** [comment]
is logging with `bunyan-loggly` sync 🤔 That is probably why it has buffer / bulk configurations: https://www.npmjs.com/package/bunyan-loggly#buffering which seems sensible.
