### ISSUE TITLE
error design

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ignition#6]
The current error design is not good enough.

```
err = new errors.NoPermissionError()
err instanceof errors.NoPermissionError
err instanceof Error
```

Both are never true.
That is because: the `new` operator is used for the function `errors.NoPermissionError` and not for the wrapped created error.

Another thing:
https://github.com/TryGhost/Patronus/blob/master/test/unit/lib_oauth.test.js#L165
Let's not compare strings!When doing a global rename, these strings are NOT affected.

**Comment by kirrg001** [comment]
I suggest to go with this solution for the next version.
https://github.com/kirrg001/Ghost/blob/c004fab3baefd9b9442ecf47b32597cab70a478a/core/server/errors.js

**Comment by ErisDS** [comment]
Agreed 👍
