### ISSUE TITLE
Ensure `empty` is not printed in stdout/stderr transport

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ignition#66]
We have recently added a protection to avoid data mismatch errors when the loggly transport is enabled.

The stdout/stderr transport now prints for context, help and errorDetails `empty`, which is sub-optimal, but not critical.

**Comment by kirrg001** [comment]
@gargol Would be cool to get a fix for that shipped. I guess it's a tiny thing?

**Comment by naz** [comment]
Sure, can it be put on a 'Monday-list'?

**Comment by kirrg001** [comment]
Absolutely 👍

**Comment by naz** [comment]
These are just some observations for future reference. 

When substituting `'empty'` with just an empty string `''` loggly index breaks. The same thing happens when sending `undefined` or `null` values.

**Comment by kirrg001** [comment]
@gargol Were you able to find a solution? This issue is still in progress on the board. I'd suggest to leave a solution conclusion as a comment and fix the issue as soon as we have time on the next bugfix Monday?

**Comment by naz** [comment]
The last state of loggly investigation was that it actually started creating searchable entries even when passed with no values. Let's def check it next Monday and close it once and for all :+1:

**Comment by kirrg001** [comment]
@gargol How long do you think it takes fixing this bug? It's pretty dominant 🤣

**Comment by ErisDS** [comment]
Is it worth closing this in favour of https://github.com/TryGhost/Ignition/issues/69? 

I'd really love a rough idea of how big a task the whole thing is - is it a Monday doable thing? Orrrrr a couple of days? Orrr?

**Comment by naz** [comment]
@ErisDS it's a Monday doable thing. The main issue is with how loggly handles their indexes when `undefined` or `''` data comes in. Last time I had a stab at it, the index had broken for a moment but then was back into the normal state in 15 minutes and was expecting any values. We can prioritize it for next Monday and have a final fix-or-close decision if that works :+1:
