### ISSUE TITLE
Order of level output is inconsistent

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ignition#72]
![order](https://user-images.githubusercontent.com/1160712/54711683-c23dbd80-4b4a-11e9-90ee-56432414f0a3.png)

^ The order of level output is sometimes before timestamp and sometimes afterwards?

Needs investigation why.

Ignition: 3.0.4

**Comment by pysysops** [comment]
@kirrg001 I would say that these 2 lines need swapping ;)

https://github.com/TryGhost/Ignition/blob/master/lib/logging/PrettyStream.js#L125-L126

**Comment by kirrg001** [comment]
Yeah that looks right 😆
